<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <title>LAZY   ~\(≧▽≦)/~</title>
    <link rel="stylesheet" href="<?php echo base_url(); ?>bootstrap/css/bootstrap.min.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="<?php echo base_url(); ?>bootstrap/js/bootstrap.min.js"></script>
    <style type="text/css">
        body{
            background-color: #f5f8fa;
        }
        .lz_panel{
            text-align: center;
            border-radius: 4px;
            border: 1px solid #d3e0e9;
            background-color: #ffffff;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
        }
        .lz_panel_content{
            padding: 15px;
        }
        .lz_panel_head{
            border-top-left-radius: 3px;
            border-top-right-radius: 3px;
            padding: 10px 15px;
            background-size: cover;
            height: 150px;
            background-image: url('<? echo base_url();?>images/iceland.jpg');
        }
        .head_icon{
            border: 3px solid #fff;
            border-radius: 100%;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
            margin-bottom: 5px;
            margin-top: -70px;
            max-width: 100px;
        }
        .title_a{
            color: inherit;
            font-size:15px;
            font-weight: bold;
            background-color: transparent;
            text-decoration: inherit;
        }
        .title_a:hover{
            color: inherit;
            text-decoration: inherit;
        }
        .list-inline li{
            border-right: 1px solid #d4dbe0;display: inline-block;  
        }
        .list-inline li:last-child {
            border-right: 0 none;
        }
        .list-inline li a{
            color: inherit;text-decoration: inherit;
        }
        .list-inline li a h5{
            margin-bottom: 0 !important;margin-top: 0 !important;font-weight: bold;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">LAZY</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">首页<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">笔记本</a></li>
                    <li><a href="#">相册</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <!-- <span class="glyphicon glyphicon-envelope"></span> -->
                            消息中心
                            <span class="badge">4</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                    <li>
                        <button style="background: transparent none repeat scroll 0 0;border: 0 none;box-shadow: none !important;outline: medium none !important;padding: 0;margin-bottom: 7px;margin-top: 7px;">
                        <img width="36" height="36" alt="Generic placeholder image" src="<? echo base_url();?>images/default_head.png" class="img-circle">
                        </button>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="lz_panel">
                    <div class="lz_panel_head">
                    </div>
                    <div class="lz_panel_content">
                        <img width="100" class="head_icon" height="100" alt="Generic placeholder image" src="<? echo base_url();?>images/default_head.png" class="img-circle">
                        <h5 style="margin-bottom: 30px !important;"><a href="#" class="title_a">你闻到他们烧焦的闻到了吗</a></h5>
                        <ul class="list-inline">
                            <li>
                                <a href="#">2233
                                    <h5>粉丝</h5>
                                </a>
                            </li>
                            <li>
                                <a href="#">522<h5>关注</h5></a>
                            </li>
                            <li>
                                <a href="#">2234<h5>微博</h5></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-6"  style="background-color:blue;">
                xxxxx
            </div>
            <div class="col-lg-3" style="background-color:green">
                ttttt
            </div>
        </div>
    </div>
</body>
</html>